Add CherryPick
resonite-modding-group/resonite-mod-manifest pull request #67
Opened 2024-05-03 14:45 UTC by FoxoBread

- [ ] The mod id matches the harmony id if used by the mod and starts with the same id as your author folder
- [ ] All used links are valid
- [ ] Your ResoniteMod.Version must match the version being added in the manifest
- [ ] Your AssemblyVersion should match the mod version
- [ ] You have included an accurate `sha256` hash for each artifact
- [ ] Do not remove old mods. Instead, use the `deprecated` flag
- [ ] Follow the [Resonite Policies and Guidelines](https://resonite.com/policies/) and [Mod Submission Guidelines](https://github.com/resonite-modding-group/resonite-mod-manifest/wiki/Submission-Guidelines)

2024-05-03 18:43 UTC, XDelta requested changes

2024-05-03 18:43 UTC, XDelta commented on manifest/net.Cyro/CherryPick/info.json
> +		"1.0.7": {
Only the latest is needed instead of adding all prior versions

2024-05-03 18:43 UTC, XDelta commented on manifest/net.Cyro/author.json
> +		"Delta": {
Should be "Cyro" here

2024-05-03 19:29 UTC, FoxoBread commented
Pardon the slight mistakes 😅

2024-05-04 02:10 UTC, XDelta commented on manifest/net.Cyro/CherryPick/info.json
> +	"description": "Simple component searching for Resonite ",
Probably good to also mention search protoflux here

2024-05-04 02:13 UTC, XDelta approved these changes

2024-05-04 02:16 UTC, merged