me and my mods
resonite-modding-group/resonite-mod-manifest pull request #9
Opened 2023-12-17 14:40 UTC by art0007i

some of the categories are wrong, I'll fix it soon™

2023-12-17 14:48 UTC, art0007i commented
ok should be good now

2023-12-20 16:19 UTC, XDelta commented on manifest/me.art0007i/🍀/info.json
> +        "2.1.0": {
Version does not match version defined in mod "2.0.0"

2023-12-21 06:11 UTC, XDelta requested changes
Version on "🍀" does not match version defined in mod

2023-12-25 16:44 UTC, XDelta approved these changes

2023-12-25 16:45 UTC, merged